[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "=1.8.12"

# Fix to resolve dependency issues within go-ethereum
[[override]]
  name = "gopkg.in/fatih/set.v0"
  version = "=0.1.0"

[prune]
  go-tests = true
